CREATE DATABASE ANTON_KIMAYEV
GO
USE ANTON_KIMAYEV
GO

CREATE SCHEMA sales
GO
CREATE SCHEMA persons
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);
BACKUP DATABASE ANTON_KIMAYEV TO DISK='C:\Users\KainWhite\Documents\University\DB\EpamLabsDB\lab1\ANTON_KIMAYEV.bak';

USE master
GO
DROP DATABASE ANTON_KIMAYEV;

RESTORE DATABASE ANTON_KIMAYEV FROM DISK = 'C:\Users\KainWhite\Documents\University\DB\EpamLabsDB\lab1\ANTON_KIMAYEV.bak';